Add templates for pos receipt and receipt link email
MyCashflow/MyCashflow-Default-Theme pull request #19
Opened 2021-12-23 09:18 UTC by J-M-P-9-6

Lisätty template PDF POS-kuitille sekä s-postitemplate POS-kuitin linkin lähettämiselle

https://github.com/MyCashflow/MyCashflow/pull/2362

2022-01-14 09:25 UTC, pulsejukka reviewed
Uudelleennimeä `emails/pos-receipt-link.html` -> `emails/receipt.html`.

2022-02-12 10:49 UTC, teemku requested changes
Tässä menee vähän hassusti tuo oikean palstan sisältö keskelle.

<img width="933" alt="image" src="https://user-images.githubusercontent.com/46671429/153708297-f5f8dc5f-45b1-4c42-875e-49bb4e9758ac.png">

2022-02-14 07:53 UTC, teemku commented on emails/pos/receipt.html
> +						<table cellpadding="18" cellspacing="0" border="0" bgcolor="#f0f0f0" height="100%" width="241">
```suggestion
						<table cellpadding="18" cellspacing="0" border="0" bgcolor="#f0f0f0" width="241">
```

Vielä ei toiminut, mutta jos tuon tuosta poistaa niin näyttäisi pelittävän.

2022-02-15 09:20 UTC, teemku approved these changes
Muutos katsottu, testasin jo aiemmin että se riitti joten en testannut uusiksi.

2022-02-15 09:22 UTC, merged